import os

INCIDENT_TIME_WINDOW_MINUTES = int(
    os.getenv("INCIDENT_TIME_WINDOW_MINUTES", "30")
)

MIN_SIMILAR_TICKETS_MEDIUM = int(
    os.getenv("MIN_SIMILAR_TICKETS_MEDIUM", "2")
)

MIN_SIMILAR_TICKETS_HIGH = int(
    os.getenv("MIN_SIMILAR_TICKETS_HIGH", "4")
)

MIN_RERANK_SCORE = float(
    os.getenv("MIN_RERANK_SCORE", "0.5")
)

SIMILARITY_THRESHOLD_HIGH = float(
    os.getenv("SIMILARITY_THRESHOLD_HIGH", "0.85")
)

SIMILARITY_THRESHOLD_MEDIUM = float(
    os.getenv("SIMILARITY_THRESHOLD_MEDIUM", "0.75")
)

MIN_SIMILAR_TICKETS = MIN_SIMILAR_TICKETS_MEDIUM
